class CountryCode {
  final String country;
  final String isoA2;
  final String isoA3;
  final String tld;
  const CountryCode({required this.country, required this.isoA2, required this.isoA3, required this.tld});
}

Map<String, CountryCode> countryCodes = {
  "Afghanistan": CountryCode(country: "Afghanistan", isoA2: "AF", isoA3: "AFG", tld: ".af"),
  "Åland Islands": CountryCode(country: "Åland Islands", isoA2: "AX", isoA3: "ALA", tld: ".ax"),
  "Albania": CountryCode(country: "Albania", isoA2: "AL", isoA3: "ALB", tld: ".al"),
  "Algeria": CountryCode(country: "Algeria", isoA2: "DZ", isoA3: "DZA", tld: ".dz"),
  "American Samoa": CountryCode(country: "American Samoa", isoA2: "AS", isoA3: "ASM", tld: ".as"),
  "Andorra": CountryCode(country: "Andorra", isoA2: "AD", isoA3: "AND", tld: ".ad"),
  "Angola": CountryCode(country: "Angola", isoA2: "AO", isoA3: "AGO", tld: ".ao"),
  "Anguilla": CountryCode(country: "Anguilla", isoA2: "AI", isoA3: "AIA", tld: ".ai"),
  "Antarctica[a]": CountryCode(country: "Antarctica[a]", isoA2: "AQ", isoA3: "ATA", tld: ".aq"),
  "Antigua and Barbuda": CountryCode(country: "Antigua and Barbuda", isoA2: "AG", isoA3: "ATG", tld: ".ag"),
  "Argentina": CountryCode(country: "Argentina", isoA2: "AR", isoA3: "ARG", tld: ".ar"),
  "Armenia": CountryCode(country: "Armenia", isoA2: "AM", isoA3: "ARM", tld: ".am"),
  "Aruba": CountryCode(country: "Aruba", isoA2: "AW", isoA3: "ABW", tld: ".aw"),
  "Australia[b]": CountryCode(country: "Australia[b]", isoA2: "AU", isoA3: "AUS", tld: ".au"),
  "Austria": CountryCode(country: "Austria", isoA2: "AT", isoA3: "AUT", tld: ".at"),
  "Azerbaijan": CountryCode(country: "Azerbaijan", isoA2: "AZ", isoA3: "AZE", tld: ".az"),
  "Bahamas (the)": CountryCode(country: "Bahamas (the)", isoA2: "BS", isoA3: "BHS", tld: ".bs"),
  "Bahrain": CountryCode(country: "Bahrain", isoA2: "BH", isoA3: "BHR", tld: ".bh"),
  "Bangladesh": CountryCode(country: "Bangladesh", isoA2: "BD", isoA3: "BGD", tld: ".bd"),
  "Barbados": CountryCode(country: "Barbados", isoA2: "BB", isoA3: "BRB", tld: ".bb"),
  "Belarus": CountryCode(country: "Belarus", isoA2: "BY", isoA3: "BLR", tld: ".by"),
  "Belgium": CountryCode(country: "Belgium", isoA2: "BE", isoA3: "BEL", tld: ".be"),
  "Belize": CountryCode(country: "Belize", isoA2: "BZ", isoA3: "BLZ", tld: ".bz"),
  "Benin": CountryCode(country: "Benin", isoA2: "BJ", isoA3: "BEN", tld: ".bj"),
  "Bermuda": CountryCode(country: "Bermuda", isoA2: "BM", isoA3: "BMU", tld: ".bm"),
  "Bhutan": CountryCode(country: "Bhutan", isoA2: "BT", isoA3: "BTN", tld: ".bt"),
  "Bolivia (Plurinational State of)": CountryCode(
    country: "Bolivia (Plurinational State of)",
    isoA2: "BO",
    isoA3: "BOL",
    tld: ".bo",
  ),
  "BonaireSint Eustatius Saba": CountryCode(
    country: "Bonaire Sint EustatiusSaba",
    isoA2: "BQ",
    isoA3: "BES",
    tld: ".bq.nl[c]",
  ),
  "Bosnia and Herzegovina": CountryCode(country: "Bosnia and Herzegovina", isoA2: "BA", isoA3: "BIH", tld: ".ba"),
  "Botswana": CountryCode(country: "Botswana", isoA2: "BW", isoA3: "BWA", tld: ".bw"),
  "Bouvet Island": CountryCode(country: "Bouvet Island", isoA2: "BV", isoA3: "BVT", tld: "[d]"),
  "Brazil": CountryCode(country: "Brazil", isoA2: "BR", isoA3: "BRA", tld: ".br"),
  "British Indian Ocean Territory (the)": CountryCode(
    country: "British Indian Ocean Territory (the)",
    isoA2: "IO",
    isoA3: "IOT",
    tld: ".io",
  ),
  "British Virgin Islands – See Virgin Islands (British).": CountryCode(
    country: "British Virgin Islands – See Virgin Islands (British).",
    isoA2: "",
    isoA3: "",
    tld: "",
  ),
  "Brunei Darussalam[e]": CountryCode(country: "Brunei Darussalam[e]", isoA2: "BN", isoA3: "BRN", tld: ".bn"),
  "Bulgaria": CountryCode(country: "Bulgaria", isoA2: "BG", isoA3: "BGR", tld: ".bg"),
  "Burkina Faso": CountryCode(country: "Burkina Faso", isoA2: "BF", isoA3: "BFA", tld: ".bf"),
  "Burundi": CountryCode(country: "Burundi", isoA2: "BI", isoA3: "BDI", tld: ".bi"),
  "Cabo Verde[f]": CountryCode(country: "Cabo Verde[f]", isoA2: "CV", isoA3: "CPV", tld: ".cv"),
  "Cambodia": CountryCode(country: "Cambodia", isoA2: "KH", isoA3: "KHM", tld: ".kh"),
  "Cameroon": CountryCode(country: "Cameroon", isoA2: "CM", isoA3: "CMR", tld: ".cm"),
  "Canada": CountryCode(country: "Canada", isoA2: "CA", isoA3: "CAN", tld: ".ca"),
  "Cayman Islands (the)": CountryCode(country: "Cayman Islands (the)", isoA2: "KY", isoA3: "CYM", tld: ".ky"),
  "Central African Republic (the)": CountryCode(
    country: "Central African Republic (the)",
    isoA2: "CF",
    isoA3: "CAF",
    tld: ".cf",
  ),
  "Chad": CountryCode(country: "Chad", isoA2: "TD", isoA3: "TCD", tld: ".td"),
  "Chile": CountryCode(country: "Chile", isoA2: "CL", isoA3: "CHL", tld: ".cl"),
  "China": CountryCode(country: "China", isoA2: "CN", isoA3: "CHN", tld: ".cn"),
  "Christmas Island": CountryCode(country: "Christmas Island", isoA2: "CX", isoA3: "CXR", tld: ".cx"),
  "Cocos (Keeling) Islands (the)": CountryCode(
    country: "Cocos (Keeling) Islands (the)",
    isoA2: "CC",
    isoA3: "CCK",
    tld: ".cc",
  ),
  "Colombia": CountryCode(country: "Colombia", isoA2: "CO", isoA3: "COL", tld: ".co"),
  "Comoros (the)": CountryCode(country: "Comoros (the)", isoA2: "KM", isoA3: "COM", tld: ".km"),
  "Congo (the Democratic Republic of the)": CountryCode(
    country: "Congo (the Democratic Republic of the)",
    isoA2: "CD",
    isoA3: "COD",
    tld: ".cd",
  ),
  "Congo (the)[g]": CountryCode(country: "Congo (the)[g]", isoA2: "CG", isoA3: "COG", tld: ".cg"),
  "Cook Islands (the)": CountryCode(country: "Cook Islands (the)", isoA2: "CK", isoA3: "COK", tld: ".ck"),
  "Costa Rica": CountryCode(country: "Costa Rica", isoA2: "CR", isoA3: "CRI", tld: ".cr"),
  "Côte d'Ivoire[h]": CountryCode(country: "Côte d'Ivoire[h]", isoA2: "CI", isoA3: "CIV", tld: ".ci"),
  "Croatia": CountryCode(country: "Croatia", isoA2: "HR", isoA3: "HRV", tld: ".hr"),
  "Cuba": CountryCode(country: "Cuba", isoA2: "CU", isoA3: "CUB", tld: ".cu"),
  "Curaçao": CountryCode(country: "Curaçao", isoA2: "CW", isoA3: "CUW", tld: ".cw"),
  "Cyprus": CountryCode(country: "Cyprus", isoA2: "CY", isoA3: "CYP", tld: ".cy"),
  "Czechia[i]": CountryCode(country: "Czechia[i]", isoA2: "CZ", isoA3: "CZE", tld: ".cz"),
  "Denmark": CountryCode(country: "Denmark", isoA2: "DK", isoA3: "DNK", tld: ".dk"),
  "Djibouti": CountryCode(country: "Djibouti", isoA2: "DJ", isoA3: "DJI", tld: ".dj"),
  "Dominica": CountryCode(country: "Dominica", isoA2: "DM", isoA3: "DMA", tld: ".dm"),
  "Dominican Republic (the)": CountryCode(country: "Dominican Republic (the)", isoA2: "DO", isoA3: "DOM", tld: ".do"),
  "Ecuador": CountryCode(country: "Ecuador", isoA2: "EC", isoA3: "ECU", tld: ".ec"),
  "Egypt": CountryCode(country: "Egypt", isoA2: "EG", isoA3: "EGY", tld: ".eg"),
  "El Salvador": CountryCode(country: "El Salvador", isoA2: "SV", isoA3: "SLV", tld: ".sv"),
  "Equatorial Guinea": CountryCode(country: "Equatorial Guinea", isoA2: "GQ", isoA3: "GNQ", tld: ".gq"),
  "Eritrea": CountryCode(country: "Eritrea", isoA2: "ER", isoA3: "ERI", tld: ".er"),
  "Estonia": CountryCode(country: "Estonia", isoA2: "EE", isoA3: "EST", tld: ".ee"),
  "Eswatini[j]": CountryCode(country: "Eswatini[j]", isoA2: "SZ", isoA3: "SWZ", tld: ".sz"),
  "Ethiopia": CountryCode(country: "Ethiopia", isoA2: "ET", isoA3: "ETH", tld: ".et"),
  "Falkland Islands (the) [Malvinas][k]": CountryCode(
    country: "Falkland Islands (the) [Malvinas][k]",
    isoA2: "FK",
    isoA3: "FLK",
    tld: ".fk",
  ),
  "Faroe Islands (the)": CountryCode(country: "Faroe Islands (the)", isoA2: "FO", isoA3: "FRO", tld: ".fo"),
  "Fiji": CountryCode(country: "Fiji", isoA2: "FJ", isoA3: "FJI", tld: ".fj"),
  "Finland": CountryCode(country: "Finland", isoA2: "FI", isoA3: "FIN", tld: ".fi"),
  "France[l]": CountryCode(country: "France[l]", isoA2: "FR", isoA3: "FRA", tld: ".fr"),
  "French Guiana": CountryCode(country: "French Guiana", isoA2: "GF", isoA3: "GUF", tld: ".gf"),
  "French Polynesia": CountryCode(country: "French Polynesia", isoA2: "PF", isoA3: "PYF", tld: ".pf"),
  "French Southern Territories (the)[m]": CountryCode(
    country: "French Southern Territories (the)[m]",
    isoA2: "TF",
    isoA3: "ATF",
    tld: ".tf",
  ),
  "Gabon": CountryCode(country: "Gabon", isoA2: "GA", isoA3: "GAB", tld: ".ga"),
  "Gambia (the)": CountryCode(country: "Gambia (the)", isoA2: "GM", isoA3: "GMB", tld: ".gm"),
  "Georgia": CountryCode(country: "Georgia", isoA2: "GE", isoA3: "GEO", tld: ".ge"),
  "Germany": CountryCode(country: "Germany", isoA2: "DE", isoA3: "DEU", tld: ".de"),
  "Ghana": CountryCode(country: "Ghana", isoA2: "GH", isoA3: "GHA", tld: ".gh"),
  "Gibraltar": CountryCode(country: "Gibraltar", isoA2: "GI", isoA3: "GIB", tld: ".gi"),
  "Greece": CountryCode(country: "Greece", isoA2: "GR", isoA3: "GRC", tld: ".gr"),
  "Greenland": CountryCode(country: "Greenland", isoA2: "GL", isoA3: "GRL", tld: ".gl"),
  "Grenada": CountryCode(country: "Grenada", isoA2: "GD", isoA3: "GRD", tld: ".gd"),
  "Guadeloupe": CountryCode(country: "Guadeloupe", isoA2: "GP", isoA3: "GLP", tld: ".gp"),
  "Guam": CountryCode(country: "Guam", isoA2: "GU", isoA3: "GUM", tld: ".gu"),
  "Guatemala": CountryCode(country: "Guatemala", isoA2: "GT", isoA3: "GTM", tld: ".gt"),
  "Guernsey": CountryCode(country: "Guernsey", isoA2: "GG", isoA3: "GGY", tld: ".gg"),
  "Guinea": CountryCode(country: "Guinea", isoA2: "GN", isoA3: "GIN", tld: ".gn"),
  "Guinea-Bissau": CountryCode(country: "Guinea-Bissau", isoA2: "GW", isoA3: "GNB", tld: ".gw"),
  "Guyana": CountryCode(country: "Guyana", isoA2: "GY", isoA3: "GUY", tld: ".gy"),
  "Haiti": CountryCode(country: "Haiti", isoA2: "HT", isoA3: "HTI", tld: ".ht"),
  "Heard Island and McDonald Islands": CountryCode(
    country: "Heard Island and McDonald Islands",
    isoA2: "HM",
    isoA3: "HMD",
    tld: ".hm",
  ),
  "Holy See (the)[n]": CountryCode(country: "Holy See (the)[n]", isoA2: "VA", isoA3: "VAT", tld: ".va"),
  "Honduras": CountryCode(country: "Honduras", isoA2: "HN", isoA3: "HND", tld: ".hn"),
  "Hong Kong": CountryCode(country: "Hong Kong", isoA2: "HK", isoA3: "HKG", tld: ".hk"),
  "Hungary": CountryCode(country: "Hungary", isoA2: "HU", isoA3: "HUN", tld: ".hu"),
  "Iceland": CountryCode(country: "Iceland", isoA2: "IS", isoA3: "ISL", tld: ".is"),
  "India": CountryCode(country: "India", isoA2: "IN", isoA3: "IND", tld: ".in"),
  "Indonesia": CountryCode(country: "Indonesia", isoA2: "ID", isoA3: "IDN", tld: ".id"),
  "Iran (Islamic Republic of)[o]": CountryCode(
    country: "Iran (Islamic Republic of)[o]",
    isoA2: "IR",
    isoA3: "IRN",
    tld: ".ir",
  ),
  "Iraq": CountryCode(country: "Iraq", isoA2: "IQ", isoA3: "IRQ", tld: ".iq"),
  "Ireland": CountryCode(country: "Ireland", isoA2: "IE", isoA3: "IRL", tld: ".ie"),
  "Isle of Man": CountryCode(country: "Isle of Man", isoA2: "IM", isoA3: "IMN", tld: ".im"),
  "Israel": CountryCode(country: "Israel", isoA2: "IL", isoA3: "ISR", tld: ".il"),
  "Italy": CountryCode(country: "Italy", isoA2: "IT", isoA3: "ITA", tld: ".it"),
  "Jamaica": CountryCode(country: "Jamaica", isoA2: "JM", isoA3: "JAM", tld: ".jm"),
  "Japan": CountryCode(country: "Japan", isoA2: "JP", isoA3: "JPN", tld: ".jp"),
  "Jersey": CountryCode(country: "Jersey", isoA2: "JE", isoA3: "JEY", tld: ".je"),
  "Jordan": CountryCode(country: "Jordan", isoA2: "JO", isoA3: "JOR", tld: ".jo"),
  "Kazakhstan": CountryCode(country: "Kazakhstan", isoA2: "KZ", isoA3: "KAZ", tld: ".kz"),
  "Kenya": CountryCode(country: "Kenya", isoA2: "KE", isoA3: "KEN", tld: ".ke"),
  "Kiribati": CountryCode(country: "Kiribati", isoA2: "KI", isoA3: "KIR", tld: ".ki"),
  "Korea (the Democratic People's Republic of)[p]": CountryCode(
    country: "Korea (the Democratic People's Republic of)[p]",
    isoA2: "KP",
    isoA3: "PRK",
    tld: ".kp",
  ),
  "Korea (the Republic of)[q]": CountryCode(
    country: "Korea (the Republic of)[q]",
    isoA2: "KR",
    isoA3: "KOR",
    tld: ".kr",
  ),
  "Kuwait": CountryCode(country: "Kuwait", isoA2: "KW", isoA3: "KWT", tld: ".kw"),
  "Kyrgyzstan": CountryCode(country: "Kyrgyzstan", isoA2: "KG", isoA3: "KGZ", tld: ".kg"),
  "Lao People's Democratic Republic (the)[r]": CountryCode(
    country: "Lao People's Democratic Republic (the)[r]",
    isoA2: "LA",
    isoA3: "LAO",
    tld: ".la",
  ),
  "Latvia": CountryCode(country: "Latvia", isoA2: "LV", isoA3: "LVA", tld: ".lv"),
  "Lebanon": CountryCode(country: "Lebanon", isoA2: "LB", isoA3: "LBN", tld: ".lb"),
  "Lesotho": CountryCode(country: "Lesotho", isoA2: "LS", isoA3: "LSO", tld: ".ls"),
  "Liberia": CountryCode(country: "Liberia", isoA2: "LR", isoA3: "LBR", tld: ".lr"),
  "Libya": CountryCode(country: "Libya", isoA2: "LY", isoA3: "LBY", tld: ".ly"),
  "Liechtenstein": CountryCode(country: "Liechtenstein", isoA2: "LI", isoA3: "LIE", tld: ".li"),
  "Lithuania": CountryCode(country: "Lithuania", isoA2: "LT", isoA3: "LTU", tld: ".lt"),
  "Luxembourg": CountryCode(country: "Luxembourg", isoA2: "LU", isoA3: "LUX", tld: ".lu"),
  "Macao[s]": CountryCode(country: "Macao[s]", isoA2: "MO", isoA3: "MAC", tld: ".mo"),
  "Madagascar": CountryCode(country: "Madagascar", isoA2: "MG", isoA3: "MDG", tld: ".mg"),
  "Malawi": CountryCode(country: "Malawi", isoA2: "MW", isoA3: "MWI", tld: ".mw"),
  "Malaysia": CountryCode(country: "Malaysia", isoA2: "MY", isoA3: "MYS", tld: ".my"),
  "Maldives": CountryCode(country: "Maldives", isoA2: "MV", isoA3: "MDV", tld: ".mv"),
  "Mali": CountryCode(country: "Mali", isoA2: "ML", isoA3: "MLI", tld: ".ml"),
  "Malta": CountryCode(country: "Malta", isoA2: "MT", isoA3: "MLT", tld: ".mt"),
  "Marshall Islands (the)": CountryCode(country: "Marshall Islands (the)", isoA2: "MH", isoA3: "MHL", tld: ".mh"),
  "Martinique": CountryCode(country: "Martinique", isoA2: "MQ", isoA3: "MTQ", tld: ".mq"),
  "Mauritania": CountryCode(country: "Mauritania", isoA2: "MR", isoA3: "MRT", tld: ".mr"),
  "Mauritius": CountryCode(country: "Mauritius", isoA2: "MU", isoA3: "MUS", tld: ".mu"),
  "Mayotte": CountryCode(country: "Mayotte", isoA2: "YT", isoA3: "MYT", tld: ".yt"),
  "Mexico": CountryCode(country: "Mexico", isoA2: "MX", isoA3: "MEX", tld: ".mx"),
  "Micronesia (Federated States of)": CountryCode(
    country: "Micronesia (Federated States of)",
    isoA2: "FM",
    isoA3: "FSM",
    tld: ".fm",
  ),
  "Moldova (the Republic of)": CountryCode(country: "Moldova (the Republic of)", isoA2: "MD", isoA3: "MDA", tld: ".md"),
  "Monaco": CountryCode(country: "Monaco", isoA2: "MC", isoA3: "MCO", tld: ".mc"),
  "Mongolia": CountryCode(country: "Mongolia", isoA2: "MN", isoA3: "MNG", tld: ".mn"),
  "Montenegro": CountryCode(country: "Montenegro", isoA2: "ME", isoA3: "MNE", tld: ".me"),
  "Montserrat": CountryCode(country: "Montserrat", isoA2: "MS", isoA3: "MSR", tld: ".ms"),
  "Morocco": CountryCode(country: "Morocco", isoA2: "MA", isoA3: "MAR", tld: ".ma"),
  "Mozambique": CountryCode(country: "Mozambique", isoA2: "MZ", isoA3: "MOZ", tld: ".mz"),
  "Myanmar[t]": CountryCode(country: "Myanmar[t]", isoA2: "MM", isoA3: "MMR", tld: ".mm"),
  "Namibia": CountryCode(country: "Namibia", isoA2: "NA", isoA3: "NAM", tld: ".na"),
  "Nauru": CountryCode(country: "Nauru", isoA2: "NR", isoA3: "NRU", tld: ".nr"),
  "Nepal": CountryCode(country: "Nepal", isoA2: "NP", isoA3: "NPL", tld: ".np"),
  "Netherlands (Kingdom of the)": CountryCode(
    country: "Netherlands (Kingdom of the)",
    isoA2: "NL",
    isoA3: "NLD",
    tld: ".nl",
  ),
  "New Caledonia": CountryCode(country: "New Caledonia", isoA2: "NC", isoA3: "NCL", tld: ".nc"),
  "New Zealand": CountryCode(country: "New Zealand", isoA2: "NZ", isoA3: "NZL", tld: ".nz"),
  "Nicaragua": CountryCode(country: "Nicaragua", isoA2: "NI", isoA3: "NIC", tld: ".ni"),
  "Niger (the)": CountryCode(country: "Niger (the)", isoA2: "NE", isoA3: "NER", tld: ".ne"),
  "Nigeria": CountryCode(country: "Nigeria", isoA2: "NG", isoA3: "NGA", tld: ".ng"),
  "Niue": CountryCode(country: "Niue", isoA2: "NU", isoA3: "NIU", tld: ".nu"),
  "Norfolk Island": CountryCode(country: "Norfolk Island", isoA2: "NF", isoA3: "NFK", tld: ".nf"),
  "North Macedonia[u]": CountryCode(country: "North Macedonia[u]", isoA2: "MK", isoA3: "MKD", tld: ".mk"),
  "Northern Mariana Islands (the)": CountryCode(
    country: "Northern Mariana Islands (the)",
    isoA2: "MP",
    isoA3: "MNP",
    tld: ".mp",
  ),
  "Norway": CountryCode(country: "Norway", isoA2: "NO", isoA3: "NOR", tld: ".no"),
  "Oman": CountryCode(country: "Oman", isoA2: "OM", isoA3: "OMN", tld: ".om"),
  "Pakistan": CountryCode(country: "Pakistan", isoA2: "PK", isoA3: "PAK", tld: ".pk"),
  "Palau": CountryCode(country: "Palau", isoA2: "PW", isoA3: "PLW", tld: ".pw"),
  "Palestine, State of": CountryCode(country: "Palestine, State of", isoA2: "PS", isoA3: "PSE", tld: ".ps"),
  "Panama": CountryCode(country: "Panama", isoA2: "PA", isoA3: "PAN", tld: ".pa"),
  "Papua New Guinea": CountryCode(country: "Papua New Guinea", isoA2: "PG", isoA3: "PNG", tld: ".pg"),
  "Paraguay": CountryCode(country: "Paraguay", isoA2: "PY", isoA3: "PRY", tld: ".py"),
  "Peru": CountryCode(country: "Peru", isoA2: "PE", isoA3: "PER", tld: ".pe"),
  "Philippines (the)": CountryCode(country: "Philippines (the)", isoA2: "PH", isoA3: "PHL", tld: ".ph"),
  "Pitcairn[v]": CountryCode(country: "Pitcairn[v]", isoA2: "PN", isoA3: "PCN", tld: ".pn"),
  "Poland": CountryCode(country: "Poland", isoA2: "PL", isoA3: "POL", tld: ".pl"),
  "Portugal": CountryCode(country: "Portugal", isoA2: "PT", isoA3: "PRT", tld: ".pt"),
  "Puerto Rico": CountryCode(country: "Puerto Rico", isoA2: "PR", isoA3: "PRI", tld: ".pr"),
  "Qatar": CountryCode(country: "Qatar", isoA2: "QA", isoA3: "QAT", tld: ".qa"),
  "Réunion": CountryCode(country: "Réunion", isoA2: "RE", isoA3: "REU", tld: ".re"),
  "Romania": CountryCode(country: "Romania", isoA2: "RO", isoA3: "ROU", tld: ".ro"),
  "Russian Federation (the)[w]": CountryCode(
    country: "Russian Federation (the)[w]",
    isoA2: "RU",
    isoA3: "RUS",
    tld: ".ru",
  ),
  "Rwanda": CountryCode(country: "Rwanda", isoA2: "RW", isoA3: "RWA", tld: ".rw"),
  "Saint Barthélemy": CountryCode(country: "Saint Barthélemy", isoA2: "BL", isoA3: "BLM", tld: ".bl"),
  "Saint Helena Ascension Island Tristan da Cunha": CountryCode(
    country: "Saint Helena Ascension Island Tristan da Cunha",
    isoA2: "SH",
    isoA3: "SHN",
    tld: ".sh",
  ),
  "Saint Kitts and Nevis": CountryCode(country: "Saint Kitts and Nevis", isoA2: "KN", isoA3: "KNA", tld: ".kn"),
  "Saint Lucia": CountryCode(country: "Saint Lucia", isoA2: "LC", isoA3: "LCA", tld: ".lc"),
  "Saint Martin (French part)": CountryCode(
    country: "Saint Martin (French part)",
    isoA2: "MF",
    isoA3: "MAF",
    tld: ".mf",
  ),
  "Saint Pierre and Miquelon": CountryCode(country: "Saint Pierre and Miquelon", isoA2: "PM", isoA3: "SPM", tld: ".pm"),
  "Saint Vincent and the Grenadines": CountryCode(
    country: "Saint Vincent and the Grenadines",
    isoA2: "VC",
    isoA3: "VCT",
    tld: ".vc",
  ),
  "Samoa": CountryCode(country: "Samoa", isoA2: "WS", isoA3: "WSM", tld: ".ws"),
  "San Marino": CountryCode(country: "San Marino", isoA2: "SM", isoA3: "SMR", tld: ".sm"),
  "Sao Tome and Principe": CountryCode(country: "Sao Tome and Principe", isoA2: "ST", isoA3: "STP", tld: ".st"),
  "Saudi Arabia": CountryCode(country: "Saudi Arabia", isoA2: "SA", isoA3: "SAU", tld: ".sa"),
  "Senegal": CountryCode(country: "Senegal", isoA2: "SN", isoA3: "SEN", tld: ".sn"),
  "Serbia": CountryCode(country: "Serbia", isoA2: "RS", isoA3: "SRB", tld: ".rs"),
  "Seychelles": CountryCode(country: "Seychelles", isoA2: "SC", isoA3: "SYC", tld: ".sc"),
  "Sierra Leone": CountryCode(country: "Sierra Leone", isoA2: "SL", isoA3: "SLE", tld: ".sl"),
  "Singapore": CountryCode(country: "Singapore", isoA2: "SG", isoA3: "SGP", tld: ".sg"),
  "Sint Maarten (Dutch part)": CountryCode(country: "Sint Maarten (Dutch part)", isoA2: "SX", isoA3: "SXM", tld: ".sx"),
  "Slovakia": CountryCode(country: "Slovakia", isoA2: "SK", isoA3: "SVK", tld: ".sk"),
  "Slovenia": CountryCode(country: "Slovenia", isoA2: "SI", isoA3: "SVN", tld: ".si"),
  "Solomon Islands": CountryCode(country: "Solomon Islands", isoA2: "SB", isoA3: "SLB", tld: ".sb"),
  "Somalia": CountryCode(country: "Somalia", isoA2: "SO", isoA3: "SOM", tld: ".so"),
  "South Africa": CountryCode(country: "South Africa", isoA2: "ZA", isoA3: "ZAF", tld: ".za"),
  "South Georgia and the South Sandwich Islands": CountryCode(
    country: "South Georgia and the South Sandwich Islands",
    isoA2: "GS",
    isoA3: "SGS",
    tld: ".gs",
  ),
  "South Sudan": CountryCode(country: "South Sudan", isoA2: "SS", isoA3: "SSD", tld: ".ss"),
  "Spain": CountryCode(country: "Spain", isoA2: "ES", isoA3: "ESP", tld: ".es"),
  "Sri Lanka": CountryCode(country: "Sri Lanka", isoA2: "LK", isoA3: "LKA", tld: ".lk"),
  "Sudan (the)": CountryCode(country: "Sudan (the)", isoA2: "SD", isoA3: "SDN", tld: ".sd"),
  "Suriname": CountryCode(country: "Suriname", isoA2: "SR", isoA3: "SUR", tld: ".sr"),
  "Svalbard Jan Mayen": CountryCode(country: "Svalbard Jan Mayen", isoA2: "SJ", isoA3: "SJM", tld: "[x]"),
  "Sweden": CountryCode(country: "Sweden", isoA2: "SE", isoA3: "SWE", tld: ".se"),
  "Switzerland": CountryCode(country: "Switzerland", isoA2: "CH", isoA3: "CHE", tld: ".ch"),
  "Syrian Arab Republic (the)[y]": CountryCode(
    country: "Syrian Arab Republic (the)[y]",
    isoA2: "SY",
    isoA3: "SYR",
    tld: ".sy",
  ),
  "Taiwan (Province of China)[z]": CountryCode(
    country: "Taiwan (Province of China)[z]",
    isoA2: "TW",
    isoA3: "TWN",
    tld: ".tw",
  ),
  "Tajikistan": CountryCode(country: "Tajikistan", isoA2: "TJ", isoA3: "TJK", tld: ".tj"),
  "Tanzania, the United Republic of": CountryCode(
    country: "Tanzania, the United Republic of",
    isoA2: "TZ",
    isoA3: "TZA",
    tld: ".tz",
  ),
  "Thailand": CountryCode(country: "Thailand", isoA2: "TH", isoA3: "THA", tld: ".th"),
  "Timor-Leste[ab]": CountryCode(country: "Timor-Leste[ab]", isoA2: "TL", isoA3: "TLS", tld: ".tl"),
  "Togo": CountryCode(country: "Togo", isoA2: "TG", isoA3: "TGO", tld: ".tg"),
  "Tokelau": CountryCode(country: "Tokelau", isoA2: "TK", isoA3: "TKL", tld: ".tk"),
  "Tonga": CountryCode(country: "Tonga", isoA2: "TO", isoA3: "TON", tld: ".to"),
  "Trinidad and Tobago": CountryCode(country: "Trinidad and Tobago", isoA2: "TT", isoA3: "TTO", tld: ".tt"),
  "Tunisia": CountryCode(country: "Tunisia", isoA2: "TN", isoA3: "TUN", tld: ".tn"),
  "Türkiye[ac]": CountryCode(country: "Türkiye[ac]", isoA2: "TR", isoA3: "TUR", tld: ".tr"),
  "Turkmenistan": CountryCode(country: "Turkmenistan", isoA2: "TM", isoA3: "TKM", tld: ".tm"),
  "Turks and Caicos Islands (the)": CountryCode(
    country: "Turks and Caicos Islands (the)",
    isoA2: "TC",
    isoA3: "TCA",
    tld: ".tc",
  ),
  "Tuvalu": CountryCode(country: "Tuvalu", isoA2: "TV", isoA3: "TUV", tld: ".tv"),
  "Uganda": CountryCode(country: "Uganda", isoA2: "UG", isoA3: "UGA", tld: ".ug"),
  "Ukraine[ad]": CountryCode(country: "Ukraine[ad]", isoA2: "UA", isoA3: "UKR", tld: ".ua"),
  "United Arab Emirates (the)": CountryCode(
    country: "United Arab Emirates (the)",
    isoA2: "AE",
    isoA3: "ARE",
    tld: ".ae",
  ),
  "United Kingdom of Great Britain and Northern Ireland (the)": CountryCode(
    country: "United Kingdom of Great Britain and Northern Ireland (the)",
    isoA2: "GB",
    isoA3: "GBR",
    tld: ".gb.uk[ae]",
  ),
  "United States Minor Outlying Islands (the)[10][af]": CountryCode(
    country: "United States Minor Outlying Islands (the)[10][af]",
    isoA2: "UM",
    isoA3: "UMI",
    tld: "[ag]",
  ),
  "United States of America (the)": CountryCode(
    country: "United States of America (the)",
    isoA2: "US",
    isoA3: "USA",
    tld: ".us",
  ),
  "Uruguay": CountryCode(country: "Uruguay", isoA2: "UY", isoA3: "URY", tld: ".uy"),
  "Uzbekistan": CountryCode(country: "Uzbekistan", isoA2: "UZ", isoA3: "UZB", tld: ".uz"),
  "Vanuatu": CountryCode(country: "Vanuatu", isoA2: "VU", isoA3: "VUT", tld: ".vu"),
  "Venezuela (Bolivarian Republic of)": CountryCode(
    country: "Venezuela (Bolivarian Republic of)",
    isoA2: "VE",
    isoA3: "VEN",
    tld: ".ve",
  ),
  "Viet Nam[ah]": CountryCode(country: "Viet Nam[ah]", isoA2: "VN", isoA3: "VNM", tld: ".vn"),
  "Virgin Islands (British)[ai]": CountryCode(
    country: "Virgin Islands (British)[ai]",
    isoA2: "VG",
    isoA3: "VGB",
    tld: ".vg",
  ),
  "Virgin Islands (U.S.)[aj]": CountryCode(country: "Virgin Islands (U.S.)[aj]", isoA2: "VI", isoA3: "VIR", tld: ".vi"),
  "Wallis and Futuna": CountryCode(country: "Wallis and Futuna", isoA2: "WF", isoA3: "WLF", tld: ".wf"),
  "Western Sahara[ak]": CountryCode(country: "Western Sahara[ak]", isoA2: "EH", isoA3: "ESH", tld: "[am]"),
  "Yemen": CountryCode(country: "Yemen", isoA2: "YE", isoA3: "YEM", tld: ".ye"),
  "Zambia": CountryCode(country: "Zambia", isoA2: "ZM", isoA3: "ZMB", tld: ".zm"),
  "Zimbabwe": CountryCode(country: "Zimbabwe", isoA2: "ZW", isoA3: "ZWE", tld: ".zw"),
};
